### ISSUE TITLE
Runtime exception

### ISSUE THREAD

**Issue by espinosaluis** [dandar3/android-google-play-services-README#1]
Thanks so much for making all this for us. This is really a lot of work.

I have been able to import everything and my project compiles well with these libraries.
I'm actually using maps and ads.
However every time I run it, I get an exception when trying to inflate the layouts that contains maps or ads. It's almost like the libs runtime are not there.

Is there anything that you think I could try? I followed all your steps.

Thanks.

**Comment by dandar3** [comment]
Thank you, you're welcome!

I know you may have done some of these already but I would go through them again.
- `android-google-play-services-maps` and `android-google-play-services-ads` added to your app Project Properties > Android > Library section;
- check the same Library section for each of these libraries and see they got green checks. If there is a problem (or thinks there is a problem) with the dependent libraries, the ADT plugin (in it's wonderful glory) will simply not complain and will continue like there is no problem. In that case it will not add those libraries to your project > Android Dependencies section and will not participate in the build.
- build APK, decode and then check the classes it complains about did end up in the APK. You can use dex2jar + jd-gui (see http://stackoverflow.com/a/4177581/308836)
- check if you're using the correct packages and classes in the layouts (check them against Google docs for the version you're using);
- look carefuly and thrown exception and scroll down through all causes, fully post it here so we can look at it (please confirm which version);
- Project > Clean > Clean all projects (+ rebuild) to get rid of the previously built files (if there's a mix of new and old). Or alternatively if you've seen similar weird behaviour with your Eclipse version, you can close Eclipse, search for `bin` and `gen` in your entire workspace, delete them, then restart Eclipse to kick in a fresh build.

That's all I can think for now, somehow I think no 2 (red crosses for dependant and sub-dependent libraries for whatever reason) is what's causing you grief here.

**Comment by espinosaluis** [comment]
Thanks for your help and for providing all those steps I could try.

From Eclipse I think everything looks fine (check attached images) so in theory the libraries should be there. (Originally my project is compiled with 3.2, but I have also tried with different versions just in case)

I also tried the tool that you suggested, but to be honest, I don't know where to look at. I can't find classes or any exceptions in those files. It's ok, it's really my fault, I should read more about what that app does, but after 3 days I'm almost about to give up. I have spent all that time trying to compile my project with the latest Google Play libraries, and after trying everything, your solution was the best, but I must still be missing something that I cannot figure out. I'm so close but I don't know what else to do. :(

![capture0](https://cloud.githubusercontent.com/assets/12634078/19602396/62bdc466-97ad-11e6-96e8-aadb693cf7aa.PNG)
![capture](https://cloud.githubusercontent.com/assets/12634078/19602400/66ec000c-97ad-11e6-9e3a-d9272ca366c1.PNG)

**Comment by dandar3** [comment]
It looks like you may have manually imported the libraries one by one or I might be wrong there. Not sure whether that is the cause, but still suggesting an easier way. See the two videos at the end of the `android-google-play-services-README` project.

We still don't have an exception stack trace to work with, so maybe if it's easier for you I could join you in a TeamViewer session - not sure about your timezone, see my email address in my profile and we'll try to meet.

**Comment by espinosaluis** [comment]
Thanks so much for that. You are very kind. I'm located at GMT+1. Today I will be out of town, but tomorrow and next week I should be available. You can let me know when is a good time for you.

Meanwhile, I have created a video showing how I do the whole process. I can also show you the stack trace, but I don't really think it's necessary because basically it crashes when it tries to create the AdView or Google map object.

https://www.youtube.com/watch?v=38VUWr5bBT8

Let me know if you see something wrong in the video, so I can try. 

Thanks again.

**Comment by dandar3** [comment]
I think you're doing it correctly, but I still cannot see the exception - it should appear in LogCat if you filter from Verbose to Error should be easier to stop or using `adb logcat` from a command line.

If you're using `SupportMapFragment` and you're getting an exception like below:

```
10-22 22:58:20.208  1435  1435 E AndroidRuntime: java.lang.NoSuchFieldError: No static field MapAttrs of type [I in class Lcom/google/android/gms/R$styleable; or its superclasses (declaration of 'com.google.android.gms.R$styleable' appears in /data/app/com.example.googleplayservicesdemo-2/base.apk)
10-22 22:58:20.208  1435  1435 E AndroidRuntime:        at com.google.android.gms.maps.GoogleMapOptions.createFromAttributes(Unknown Source)
10-22 22:58:20.208  1435  1435 E AndroidRuntime:        at com.google.android.gms.maps.SupportMapFragment.onInflate(Unknown Source)
10-22 22:58:20.208  1435  1435 E AndroidRuntime:        at android.support.v4.app.Fragment.onInflate(Fragment.java:1174)
10-22 22:58:20.208  1435  1435 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2414)
10-22 22:58:20.208  1435  1435 E AndroidRuntime:        at android.support.v4.app.FragmentController.onCreateView(FragmentController.java:120)
10-22 22:58:20.208  1435  1435 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:376)
10-22 22:58:20.208  1435  1435 E AndroidRuntime:        at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:33)
10-22 22:58:20.208  1435  1435 E AndroidRuntime:        at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:75)
10-22 22:58:20.208  1435  1435 E AndroidRuntime:        at com.example.googleplayservicesdemo.MainActivity.onCreateView(MainActivity.java:1)
...
```

it's because of this issue that was ignored by Google [issue 7432](https://code.google.com/p/gmaps-api-issues/issues/detail?id=7432) and the reason behind it it's quite stupid (and maybe not so stupid if Android Studio builds things differently, see my thoughts below). They split the GPS library into separate module and they're importing the wrong styleable (`com.google.android.gms.R.styleable`) in GoogleMapOptions. MapOptions styleable exists in maps library, but that compiles in `com.google.android.gms.maps` package. 

A solution would be to move the `MapAttrs` styleable from `values.xml` in `google-play-services-maps` into `google-play-services-basement`. It is a solution that I don't like cause it means fiddling with Google's code and I should need to manually fix this with every release.

It might go on with some R.string issues, I've no idea how it works in Android Studio I haven't look at it, the build process might merge the modules togther so that attrs and strings are all compiled together in the package that the code later expects. 

I've seen a somewhat similar issue for ads (see [this issue](https://github.com/dandar3/android-google-play-services-ads/issues/1#issuecomment-231530356)) - I believe the developer later replied by email that he ended up creating the AdView from code rather than XML and it worked for him.

Anyway will look at it together if you want, maybe we can figure out a way. I should be online tomorrow past 15:00 GMT+1, send me an email whenever you are online.

**Comment by espinosaluis** [comment]
You are a genius, dandar3! :)

I got ads fixed by moving:
`<declare-styleable name="AdsAttrs"><attr format="string" name="adSize"/><attr format="string" name="adSizes"/><attr format="string" name="adUnitId"/></declare-styleable>`

and maps by moving:
`<declare-styleable name="MapAttrs"><attr format="enum" name="mapType"> ...`

Both to `google-play-services-basement`

Thanks so much for all your help and for guiding me during all this process. 
I really appreciate that you created these libraries for us and hopefully you will be able to keep them updated.

Before finding your libraries, I migrated my project to Android Studio and everything worked ok after some tweaking, but it was so painfully slow to me. It basically kills my computer. I tried all possible suggestions but couldn't make it better. It also looked very unreliable. Sometimes when launching the app it wouldn't show up while debugging. I had to restart the phone, unplug it, restart Android Studio...
So that's why I decided to go back to Eclipse. It obviously has many limitations but once you have it configured correctly, it's very fast.

Regards.

**Comment by dandar3** [comment]
That's great stuff! 👍 I'll have a look at Android Studio builds and see what makes it work as it is in there.

I know what you mean - you need a bit more RAM (12-16 GB ideally) to benefit from the Gradle daemon, although Eclipse has its quirks mostly due to how ADT plugin was written, but it may be a more familiar face for some, for now anyway. What you hit was possibly some ADB issue. 

As a side note, keep an eye on **Eclipse Andmore** ([@Eclipse](https://projects.eclipse.org/projects/tools.andmore) and [@Github](https://github.com/eclipse/andmore)), they're trying to take Eclipse away from ADT and further with a new plugin. There's a request for [supporting AARs](https://bugs.eclipse.org/bugs/show_bug.cgi?id=459569).

Either way, I will continue making these libraries available here for as long as people are watching / strarring them (making Google Play Services 9.8.0 and Android Support 25.0.0 available in the next few days).

**Comment by espinosaluis** [comment]
That's awesome. Thanks! 
I will also take at look a Eclipse Andmore. I saw a reference a couple of days ago, but I haven't checked it out yet. Sounds promising.

Take care
